/*
 * Logic simlator
 * Author: Martin Krcma
 */
package logicSimulator.ui;

/**
 *
 * @author Martin
 */
public class LibraryModuleInfo extends javax.swing.JPanel {

    /**
     * Creates new form LibraryModuleInfo
     */
    public LibraryModuleInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneDocumentation = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabelCircuitImage = new LabelHQ();
        jLabelName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jSplitPane1.setResizeWeight(0.5);

        jEditorPaneDocumentation.setEditable(false);
        jEditorPaneDocumentation.setBackground(new java.awt.Color(255, 255, 255));
        jEditorPaneDocumentation.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(jEditorPaneDocumentation);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCircuitImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane2.setViewportView(jLabelCircuitImage);

        jSplitPane1.setRightComponent(jScrollPane2);

        jLabelName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelName.setText("name");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Module name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JEditorPane jEditorPaneDocumentation;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelCircuitImage;
    public javax.swing.JLabel jLabelName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
