/* 
 * Copyright (C) 2020 Martin Krcma
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package window;

import java.awt.Point;
import java.awt.Graphics;
import java.awt.Graphics2D;
import logicSimulator.Tools;
import javax.swing.ImageIcon;
import logicSimulator.projectFile.HexEditor;
import logicSimulator.projectFile.ModuleEditor;
import logicSimulator.Project;
import logicSimulator.ProjectFile;
import logicSimulator.projectFile.WorkSpace;
import logicSimulator.objects.LogicModule;
import logicSimulator.projectFile.DocumentationEditor;
import logicSimulator.ui.LSButton;

/**
 *
 * @author Martin
 */
public class NewFile extends javax.swing.JFrame {

    private Project project = null;

    private MainWindow window = null;

    /**
     * Creates new form NewFile
     *
     * @param window Main window
     * @param project Project
     */
    public NewFile(MainWindow window, Project project) {
        initComponents();
        //load project and MainWindow
        this.window = window;
        this.project = project;
        //center location
        super.setLocationRelativeTo(window);
        this.jListFiles.setSelectedIndex(0);
        this.update();
    }

    private void update() {
        //info
        String fileType = "";
        ImageIcon img = null;
        try {
            switch (this.jListFiles.getSelectedValue()) {
                case "Workspace":
                    img = new ImageIcon(this.getClass().getResource("/src/img/workspace_animation.gif"));
                    fileType = "." + logicSimulator.LogicSimulatorCore.WORKSPACE_FILE_TYPE;
                    break;
                case "Logic module":
                    img = null;
                    fileType = "." + logicSimulator.LogicSimulatorCore.MODULE_FILE_TYPE;
                    break;
                case "HEX editor":
                    img = null;
                    fileType = "." + logicSimulator.LogicSimulatorCore.HEX_FILE_TYPE;
                    break;
                case "Documentation":
                    img = null;
                    fileType = "." + logicSimulator.LogicSimulatorCore.DOCUMENTATION_FILE_TYPE;
                    break;
            }
        } catch (Exception ex) {
        }
        //display location
        this.jLabelLocation.setText(
                this.project.getFile().getAbsoluteFile().getParent()
                + "\\" + this.jTextFieldName.getText() + fileType
        );
        //project info
        this.jLabelProject.setText(this.project.getName());
        //set image
        this.jLabelGif.setIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGif = new javax.swing.JLabel(){
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                Tools.setHighQuality(g2);
                super.paintComponent((Graphics2D) g);
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFiles = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelLocation = new javax.swing.JLabel();
        jLabelProject = new javax.swing.JLabel();
        jButtonAdd = new LSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New file");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabelGif.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Files", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jListFiles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jListFiles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Workspace", "Logic module", "Script module", "HEX editor", "Documentation" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListFiles.setSelectionBackground(new java.awt.Color(80, 80, 80));
        jListFiles.setSelectionForeground(new java.awt.Color(230, 230, 230));
        jListFiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jListFilesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jListFiles);

        jPanel1.setBackground(new java.awt.Color(120, 120, 120));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setText("Name:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 235, 235));
        jLabel1.setText("Location:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 235, 235));
        jLabel3.setText("Project:");

        jTextFieldName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyReleased(evt);
            }
        });

        jLabelLocation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelLocation.setForeground(new java.awt.Color(235, 235, 235));
        jLabelLocation.setText(" ");

        jLabelProject.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelProject.setForeground(new java.awt.Color(235, 235, 235));
        jLabelProject.setText(" ");

        jButtonAdd.setBackground(new java.awt.Color(61, 61, 61));
        jButtonAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(235, 235, 235));
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelProject))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelGif, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(jLabelGif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListFilesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListFilesMouseReleased
        this.update();
    }//GEN-LAST:event_jListFilesMouseReleased

    private void jTextFieldNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyReleased
        if (evt.getKeyChar() == '.' || evt.getKeyChar() == ' ' || evt.getKeyChar() == '=') {
            this.jTextFieldName.setText(this.lastName);
        }
        this.update();
        this.lastName = this.jTextFieldName.getText();
    }//GEN-LAST:event_jTextFieldNameKeyReleased

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if (this.lastName.length() == 0) {
            return;
        }

        //add file
        ProjectFile pf = null;
        Class<?> fileType = null;
        switch (this.jListFiles.getSelectedValue()) {
            case "Workspace":
            pf = new WorkSpace(this.lastName, this.project);
            fileType = WorkSpace.class;
            break;
            case "Logic module":
            pf = new ModuleEditor(this.lastName, this.project, new LogicModule(new Point(0, 0), this.lastName));
            fileType = ModuleEditor.class;
            break;
            case "HEX editor":
            pf = new HexEditor(this.lastName, this.project);
            fileType = HexEditor.class;
            break;
            case "Documentation":
            pf = new DocumentationEditor(this.lastName, this.project);
            fileType = DocumentationEditor.class;
            break;
        }

        if (pf != null) {

            //if name exist then return
            for (ProjectFile pf2 : this.project.getProjectFiles()) {
                try {
                    if (pf2.getComp().getName().endsWith(this.lastName)) {
                        if (fileType.isInstance(pf2)) {
                            return;
                        }
                    }
                } catch (Exception ex) {
                }
            }

            //add file to project add display it
            this.window.getPFDockingPanel().displayProjectFile(pf);
            this.project.getProjectFiles().add(pf);
            this.window.updateProjectView();

            //refresh layout of docking pane
            this.window.getPFDockingPanel().refreshLayout();

            //dispose this window
            dispose();
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private String lastName = "";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelGif;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelProject;
    private javax.swing.JList<String> jListFiles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
