/*
 * Logic simlator
 * Author: Martin Krcma
 */
package window;

import logicSimulator.data.IOProject;
import logicSimulator.data.PropertieReader;
import logicSimulator.data.PropertieWriter;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import logicSimulator.LSComponent;
import logicSimulator.LogicSimulatorCore;
import logicSimulator.Project;
import logicSimulator.projectFile.WorkSpace;
import logicSimulator.common.Propertie;
import logicSimulator.Tools;
import logicSimulator.ui.LSButton;
import logicSimulator.ui.LSTextField;
import logicSimulator.ui.SystemResources;

/**
 *
 * @author Martin
 */
public class ProjectWizard extends javax.swing.JDialog implements LSComponent {

    private LogicSimulatorCore core;

    private final JFileChooser chooser = new JFileChooser();

    /**
     * Creates new form ProjectWizard_
     *
     * @param parent Parent component
     * @param modal Modal
     */
    public ProjectWizard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(
                (screen.width - this.getWidth()) / 2,
                (screen.height - this.getHeight()) / 2
        );
        this.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jButtonOpenProject = new LSButton();
        jButtonNewProject = new LSButton();
        jLabel3 = new javax.swing.JLabel();
        jPanelNewProject = new javax.swing.JPanel();
        jButtonBack = new LSButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonCreateProject = new LSButton();
        jTextFieldProjectName = new LSTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLocation1 = new LSTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelNewLibrary = new javax.swing.JPanel();
        jButtonBack1 = new LSButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonCreateProject1 = new LSButton();
        jTextField3 = new LSTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new LSTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                //draw image on background of panel
                Graphics2D g2 = (Graphics2D)g;
                Tools.setHighQuality(g2);
                g2.clearRect(0, 0, this.getWidth(), this.getHeight());
                BufferedImage imgBG = SystemResources.PROJECT_WIZARD_BG;
                float f = (float)this.getHeight() / (float)imgBG.getHeight();
                BufferedImage img = Tools.resizeImage(
                    imgBG,
                    (int)((float)imgBG.getWidth() * f),
                    this.getHeight()
                );
                g2.drawImage(
                    img,
                    this.getWidth() - img.getWidth(),
                    this.getHeight() - img.getHeight(), null);
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        jListLastProjects = new javax.swing.JList<>(){
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                Tools.setHighQuality(g2);
                super.paintComponent((Graphics2D) g);
            }
        };
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanelMain.setMinimumSize(new java.awt.Dimension(394, 546));
        jPanelMain.setOpaque(false);

        jButtonOpenProject.setBackground(new java.awt.Color(51, 51, 51));
        jButtonOpenProject.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButtonOpenProject.setForeground(new java.awt.Color(0, 0, 0));
        jButtonOpenProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/openProject.png"))); // NOI18N
        jButtonOpenProject.setText("Open project");
        jButtonOpenProject.setBorderPainted(false);
        jButtonOpenProject.setFocusPainted(false);
        jButtonOpenProject.setFocusable(false);
        jButtonOpenProject.setOpaque(false);
        jButtonOpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenProjectActionPerformed(evt);
            }
        });

        jButtonNewProject.setBackground(new Color(50, 50, 50, 130));
        jButtonNewProject.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButtonNewProject.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNewProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/newProject.png"))); // NOI18N
        jButtonNewProject.setText("New project");
        jButtonNewProject.setBorderPainted(false);
        jButtonNewProject.setFocusPainted(false);
        jButtonNewProject.setFocusable(false);
        jButtonNewProject.setOpaque(false);
        jButtonNewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewProjectActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Created by Martin Krčma");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonNewProject, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenProject, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButtonNewProject, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOpenProject, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanelNewProject.setMinimumSize(new java.awt.Dimension(394, 546));
        jPanelNewProject.setOpaque(false);

        jButtonBack.setBackground(new java.awt.Color(51, 51, 51));
        jButtonBack.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBack.setText("Back");
        jButtonBack.setBorderPainted(false);
        jButtonBack.setFocusPainted(false);
        jButtonBack.setFocusable(false);
        jButtonBack.setOpaque(false);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Created by Martin Krčma");
        jLabel4.setOpaque(true);

        jButtonCreateProject.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCreateProject.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButtonCreateProject.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCreateProject.setText("Create");
        jButtonCreateProject.setBorderPainted(false);
        jButtonCreateProject.setFocusPainted(false);
        jButtonCreateProject.setFocusable(false);
        jButtonCreateProject.setOpaque(false);
        jButtonCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateProjectActionPerformed(evt);
            }
        });

        jTextFieldProjectName.setBackground(new java.awt.Color(40, 40, 40));
        jTextFieldProjectName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldProjectName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldProjectName.setOpaque(false);
        jTextFieldProjectName.setSelectionColor(new java.awt.Color(30, 30, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Location");

        jTextFieldLocation1.setBackground(new java.awt.Color(40, 40, 40));
        jTextFieldLocation1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldLocation1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldLocation1.setOpaque(false);
        jTextFieldLocation1.setSelectionColor(new java.awt.Color(30, 30, 40));
        jTextFieldLocation1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldLocation1MousePressed(evt);
            }
        });
        jTextFieldLocation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLocation1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        jLabel7.setText("Create new project");

        javax.swing.GroupLayout jPanelNewProjectLayout = new javax.swing.GroupLayout(jPanelNewProject);
        jPanelNewProject.setLayout(jPanelNewProjectLayout);
        jPanelNewProjectLayout.setHorizontalGroup(
            jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNewProjectLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewProjectLayout.createSequentialGroup()
                        .addGroup(jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNewProjectLayout.createSequentialGroup()
                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 142, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNewProjectLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelNewProjectLayout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jButtonCreateProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelNewProjectLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldLocation1)
                                            .addComponent(jTextFieldProjectName))))))
                        .addGap(15, 15, 15))))
        );
        jPanelNewProjectLayout.setVerticalGroup(
            jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewProjectLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addComponent(jButtonCreateProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addGroup(jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanelNewLibrary.setMinimumSize(new java.awt.Dimension(394, 546));
        jPanelNewLibrary.setOpaque(false);

        jButtonBack1.setBackground(new java.awt.Color(51, 51, 51));
        jButtonBack1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButtonBack1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBack1.setText("Back");
        jButtonBack1.setBorderPainted(false);
        jButtonBack1.setFocusPainted(false);
        jButtonBack1.setFocusable(false);
        jButtonBack1.setOpaque(false);
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Created by Martin Krčma");
        jLabel8.setOpaque(true);

        jButtonCreateProject1.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCreateProject1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButtonCreateProject1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCreateProject1.setText("Create");
        jButtonCreateProject1.setBorderPainted(false);
        jButtonCreateProject1.setFocusPainted(false);
        jButtonCreateProject1.setFocusable(false);
        jButtonCreateProject1.setOpaque(false);
        jButtonCreateProject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateProject1ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(40, 40, 40));
        jTextField3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setOpaque(false);
        jTextField3.setSelectionColor(new java.awt.Color(30, 30, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Name");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Location");

        jTextField4.setBackground(new java.awt.Color(40, 40, 40));
        jTextField4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setOpaque(false);
        jTextField4.setSelectionColor(new java.awt.Color(30, 30, 40));

        jLabel11.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        jLabel11.setText("Create new library");

        javax.swing.GroupLayout jPanelNewLibraryLayout = new javax.swing.GroupLayout(jPanelNewLibrary);
        jPanelNewLibrary.setLayout(jPanelNewLibraryLayout);
        jPanelNewLibraryLayout.setHorizontalGroup(
            jPanelNewLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewLibraryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNewLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNewLibraryLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewLibraryLayout.createSequentialGroup()
                        .addGroup(jPanelNewLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNewLibraryLayout.createSequentialGroup()
                                .addComponent(jButtonBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 142, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNewLibraryLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanelNewLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(jPanelNewLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelNewLibraryLayout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jButtonCreateProject1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelNewLibraryLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelNewLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField4)
                                            .addComponent(jTextField3))))))
                        .addGap(15, 15, 15))))
        );
        jPanelNewLibraryLayout.setVerticalGroup(
            jPanelNewLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewLibraryLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNewLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(38, 38, 38)
                .addComponent(jButtonCreateProject1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addGroup(jPanelNewLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBack1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HL simulator");
        setIconImage(SystemResources.ICON);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jListLastProjects.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jListLastProjects.setModel(new DefaultListModel());
        jListLastProjects.setToolTipText("");
        jListLastProjects.setCellRenderer(new ProjectsListCellRenderer());
        jListLastProjects.setOpaque(false);
        jListLastProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jListLastProjectsMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jListLastProjects);

        jLabel2.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        jLabel2.setText("Last projects");

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dubai Light", 0, 48)); // NOI18N
        jLabel1.setIcon(new ImageIcon(Tools.resizeImage(SystemResources.ICON, 30, 30)));
        jLabel1.setText("HL simulator");

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenProjectActionPerformed
        this.chooser.setDialogTitle("Open project");
        this.chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else if (f.getName().endsWith("." + LogicSimulatorCore.PROJECT_FILE_TYPE)) {
                    return true;
                } else {
                    return false;
                }
            }

            @Override
            public String getDescription() {
                return "HL simulator project file";
            }
        });
        //show file open dialog and the open project
        if (this.chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = this.chooser.getSelectedFile();
            Project project = new Project(Tools.fileName(f.getName()));
            IOProject io = new IOProject(project);
            try {
                //open project
                io.open(f.toString());
                project.init(this.core, null);
                this.core.getLSComponents().add(project);
                //add this project to last project list
                io.addToLastProjectList();
                //close this wizzard
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Cant open project", "Error", JOptionPane.ERROR_MESSAGE, null);
            }
        }
    }//GEN-LAST:event_jButtonOpenProjectActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showMainMenu();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        showMainMenu();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateProjectActionPerformed
        try {
            //constrains
            if (this.jTextFieldProjectName.getText().length() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Project must have name", "Error", JOptionPane.ERROR_MESSAGE, null);
                return;
            }
            if (this.jTextFieldLocation1.getText().length() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Project must have location on disk", "Error", JOptionPane.ERROR_MESSAGE, null);
                return;
            }
            //drop last project
            Tools.removeProject(this.core);

            //add new project
            Project project = new Project(this.jTextFieldProjectName.getText());
            project.setFile(new File(this.jTextFieldLocation1.getText()));
            project.init(this.core, null);
            //add main workspace
            WorkSpace w = new WorkSpace("Main", project);
            project.getProjectFiles().add(w);
            project.setSelectedFile(w);
            //add logic system core
            this.core.getLSComponents().add(project);
            project.init(this.core, null);

            //save project
            IOProject io = new IOProject(project);
            try {
                io.save(new File(this.jTextFieldLocation1.getText()));
            } catch (IOException ex) {
                Logger.getLogger(ProjectWizard.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Project could not be saved", "Error", JOptionPane.ERROR_MESSAGE, null);
            }
            dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButtonCreateProjectActionPerformed

    private void jButtonCreateProject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateProject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateProject1ActionPerformed

    private void jButtonNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewProjectActionPerformed
        showNewProject();
    }//GEN-LAST:event_jButtonNewProjectActionPerformed

    private void jTextFieldLocation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLocation1ActionPerformed

    }//GEN-LAST:event_jTextFieldLocation1ActionPerformed

    private void jTextFieldLocation1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldLocation1MousePressed
        //set save path for project
        this.chooser.setDialogTitle("Project location");
        //set selected file if some is in text field
        if (this.jTextFieldLocation1.getText().length() != 0) {
            try {
                this.chooser.setSelectedFile(new File(this.jTextFieldLocation1.getText()));
            } catch (Exception ex) {
            }
        } else {
            if (this.jTextFieldProjectName.getText().length() == 0) {
                this.jTextFieldProjectName.setText("Project 1");
            }
            this.chooser.setSelectedFile(new File(this.jTextFieldProjectName.getText().replaceAll("\\s", "")
                    + "." + LogicSimulatorCore.PROJECT_FILE_TYPE));
        }
        if (this.chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.jTextFieldLocation1.setText(chooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_jTextFieldLocation1MousePressed

    private void jListLastProjectsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListLastProjectsMouseReleased
        //choose one from list with last opened project and open it
        int index = this.jListLastProjects.getSelectedIndex();
        if (index >= 0 && index < this.lastProjects.size()) {
            Tools.removeProject(this.core);
            Propertie last = this.lastProjects.get(index);
            Project project = new Project(last.getName());
            IOProject io = new IOProject(project);
            try {
                //file of project from linker list
                File projectFile = new File(last.getValueString().split(";")[0]);
                //if this file on exist than remove from list
                if (!projectFile.exists()) {
                    JOptionPane.showMessageDialog(this, "Project not found", "Error", JOptionPane.ERROR_MESSAGE, null);
                    //remove this project from list
                    PropertieWriter writer = new PropertieWriter(LogicSimulatorCore.PROPT_PROJECTS);
                    this.lastProjects.remove(last);
                    showAllLastProjects(this.lastProjects);
                    try {
                        writer.writeFile(this.lastProjects);
                    } catch (Exception ex1) {
                        Logger.getLogger(ProjectWizard.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                } else {
                    //opent project
                    io.open(projectFile.getPath());
                    project.init(this.core, null);
                    this.core.getLSComponents().add(project);
                    dispose();
                }
            } catch (Exception ex) {
                Logger.getLogger(ProjectWizard.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Cant open project", "Error", JOptionPane.ERROR_MESSAGE, null);
            }
        }
    }//GEN-LAST:event_jListLastProjectsMouseReleased

    /**
     * Show main menu
     */
    private void showMainMenu() {
        this.jPanel1.removeAll();
        this.jPanelMain.setBounds(0, 0, this.jPanel1.getWidth(), this.jPanel1.getHeight());
        this.jPanel1.add(this.jPanelMain);
        this.jPanel1.revalidate();
        this.jPanel1.repaint();
    }

    /**
     * Show new project menu
     */
    private void showNewProject() {
        this.jPanel1.removeAll();
        this.jPanelNewProject.setBounds(0, 0, this.jPanel1.getWidth(), this.jPanel1.getHeight());
        this.jPanel1.add(this.jPanelNewProject);
        this.jPanel1.revalidate();
        this.jPanel1.repaint();
    }

    /**
     * Show open project menu
     */
    private void showOpenProject() {

    }

    @Override
    public void init(LogicSimulatorCore core, PropertieReader propt) throws Exception {
        this.core = core;
        //show all last project in list
        try {
            if (propt != null) {
                List<Propertie> propts = propt.readFile();
                showAllLastProjects(propts);
            }
        } catch (IOException ex) {
        }
    }

    @Override
    public void run() {
    }

    @Override
    public void stop() {
        dispose();
    }

    private List<Propertie> lastProjects;

    private void showAllLastProjects(List<Propertie> lastProjects) {
        this.lastProjects = lastProjects;
        DefaultListModel model = (DefaultListModel) this.jListLastProjects.getModel();
        model.clear();
        //model.addElement(new String[]{"Project 1", "17:23 - 23.11.2019", "C:/Disk1/Ad/projectk.lsp", phl});
        lastProjects.forEach((propt) -> {
            try {
                //0 - time, 1 - rpoject location
                String[] arr = propt.getValueString().split(";");
                model.addElement(new String[]{
                    propt.getName(), //name
                    arr[1], //time of last change
                    arr[0], //file location
                    Tools.fileType((new File(arr[0])).getName()) //file type
                });
            } catch (Exception ex) {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonCreateProject;
    private javax.swing.JButton jButtonCreateProject1;
    private javax.swing.JButton jButtonNewProject;
    private javax.swing.JButton jButtonOpenProject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListLastProjects;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNewLibrary;
    private javax.swing.JPanel jPanelNewProject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldLocation1;
    private javax.swing.JTextField jTextFieldProjectName;
    // End of variables declaration//GEN-END:variables

    private class ProjectsListCellRenderer extends DefaultListCellRenderer {

        @Override
        public Component getListCellRendererComponent(
                JList list,
                Object value,
                int index,
                boolean isSelected,
                boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            JLabel line = new JLabel();
            line.setOpaque(true);
            //name, time, file, type
            String[] data = (String[]) value;
            //img
            String img = "";
            try {
                //create path for image icon for project, library ...
                switch (data[3]) {
                    case LogicSimulatorCore.PROJECT_FILE_TYPE:
                        img = this.getClass().getResource("/src/img/project.png").toURI().toString();
                        break;
                }
                //place image path to html img
                img = "<img src=\"" + img + "\" width=\"50\" height=\"50\" />";
            } catch (Exception ex) {
            }
            //build html for this cell
            String text = "<html><table>"
                    + "<tbody>"
                    + "<tr>"
                    + "<td>" + img + "</td>"
                    + "<td>"
                    + "<p><strong>" + data[0] + "</strong></p>"
                    + "<p>" + data[1] + "</p>"
                    + "<p>" + data[2] + "</p>"
                    + "</td>"
                    + "</tr>"
                    + "</tbody>"
                    + "</table></html>";
            line.setText(text);
            line.setFont(list.getFont());
            line.setBackground(new Color(40, 40, 40, isSelected ? 170 : 140));
            line.setForeground(Color.WHITE);
            return line;
        }
    }
}
